export const Envs = {
  BACKEND_BASE_URL: process.env.BACKEND_BASE_URL,
  NEXT_PUBLIC_BACKEND_BASE_URL: process.env.NEXT_PUBLIC_BACKEND_BASE_URL,
  NEXT_PUBLIC_BACKEND_STATIC_URL: process.env.NEXT_PUBLIC_BACKEND_STATIC_URL,
};
